apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: postgresdatabases.postgres.database.k8s.jkroepke.de
spec:
  group: postgres.database.k8s.jkroepke.de
  names:
    kind: PostgresDatabase
    listKind: PostgresDatabaseList
    plural: postgresdatabases
    singular: postgresdatabase
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      description: PostgresDatabase is the Schema for the postgresdatabases API
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          description: PostgresDatabaseSpec defines the desired state of PostgresDatabase
          type: object
          required:
            - secretName
          properties:
            secretName:
              type: string
            encoding:
              type: string
            lcCollate:
              type: string
            lcCtype:
              type: string
        status:
          description: PostgresDatabaseStatus defines the observed state of PostgresDatabase
          type: object
      type: object
  version: v1alpha1
  versions:
    - name: v1alpha1
      served: true
      storage: true
