apiVersion: v1
kind: Secret
metadata:
  name: postgres-database-operator
data:
  POSTGRES_PASSWORD: {{ .Values.postgresql.password | b64enc | quote }}
  {{- if .Values.postgresql.bgBouncerAuthQuerySupport }}
  PGBOUNCER_AUTH_QUERY_DB_PASSWORD: {{ .Values.postgresql.bgBouncerAuthQueryDbPassword | b64enc | quote }}
  {{- end }}
